2021-09-15 suggestions
slyon/ubuntu-mir pull request #1
Opened 2021-09-15 15:18 UTC by slyon

Some suggested updates to the wiki at https://wiki.ubuntu.com/MainInclusionProcess

2021-09-16 07:12 UTC, cpaelzer requested changes
Mostly +1, but some suggestions/feedback in a few places

2021-09-16 07:12 UTC, cpaelzer commented on wiki.md
> - 1. The submitter should then take responsibility for adding the package to the seeds as per SeedManagement or adding a dependency to it from another package that already is in `main`.
I think you removed the "adding the package to the seeds" line by accident?

2021-09-16 07:12 UTC, cpaelzer commented on wiki.md
> + * If a new source package contains only code which is already in main (e.g. the result of a source package split or rename, or source packages with a version in the name), it may not need a full rev
... or updating/extending on the existing old MIR bug and re-opening it by setting it to "NEW"

2021-09-16 07:12 UTC, cpaelzer commented on wiki.md
> +  * All packages must have a designated "owning" team, regardless of complexity, which is set as a package bug contact. This is not a requirement for the MIR team ACK, but for the package to be promo
Good to adapt that to the rules, I'd still want to mention that while not strictly required anymore it still is strongly suggested to subscribe as the team will get a preview of the to-be-expected incoming bugs later on once they are responsible.

2021-09-16 07:12 UTC, cpaelzer commented on wiki.md
> -TODO: - The package has a team bug subscriber
maybe move this line up to "Recommended TODOs" there we could remove it (if already subscribed) or keep it as recommendation

2021-09-16 07:12 UTC, cpaelzer commented on wiki.md
> +TODO:   (usage is OK inside tests)
I'd prefer this to be in the same line

2021-09-16 14:55 UTC, slyon commented on wiki.md
> - 1. The submitter should then take responsibility for adding the package to the seeds as per SeedManagement or adding a dependency to it from another package that already is in `main`.
No. IMO this is a duplication of the 2nd point above: "Add the package to a [[SeedManagement|seed]], or as a dependency of a package in `main`.  The package will not be moved to main automatically, but will show up in the [[http://people.ubuntu.com/~ubuntu-archive/component-mismatches.txt|component-mismatches]] list, or if the dependency is only in proposed, the [[http://people.canonical.com/~ubuntu-archive/component-mismatches-proposed.txt|component-mismatches-proposed]] list."

2021-09-16 15:09 UTC, slyon commented on wiki.md
> -TODO: - The package has a team bug subscriber
done.

2021-09-16 19:58 UTC, setharnold commented on wiki.md
> - 1. The submitter should then take responsibility for adding the package to the seeds as per SeedManagement or adding a dependency to it from another package that already is in `main`.
But someone needs to do seed management; does this change who is expected to prepare the work?

2021-09-16 19:59 UTC, setharnold commented on wiki.md
> +    2. not to build any vendored (i.e. embedded) code in the source package whose binaries appear in the archive (e.g. test code is ok) without clear justification from the requesting team and approv
It is the tiniest of nits, but I've been switching to 'ie' and 'eg' myself, because 'i.e.' and 'e.g.' take longer to type and take up more space than I think they deserve.

2021-09-20 07:31 UTC, didrocks commented on wiki.md
> - 1. The submitter should then take responsibility for adding the package to the seeds as per SeedManagement or adding a dependency to it from another package that already is in `main`.
I agree here, we need to define clearly who is expected to prepare the work, and this is the submitter responsability IMHO

2021-09-20 08:33 UTC, slyon commented on wiki.md
> - 1. The submitter should then take responsibility for adding the package to the seeds as per SeedManagement or adding a dependency to it from another package that already is in `main`.
Ok, thanks for all the comments. I merged this sentence with the sentence in L84 to clarify that it's the submitters responsibility.

2021-09-20 08:34 UTC, slyon commented on wiki.md
> +    2. not to build any vendored (i.e. embedded) code in the source package whose binaries appear in the archive (e.g. test code is ok) without clear justification from the requesting team and approv
I see your point of "i.e." being cumbersome to write, but we don't need to update the wiki pages that often, so I'd rather stick to the official form of writing, to avoid any confusion.

2021-09-22 07:25 UTC, merged